(function() {var implementors = {};
implementors['compress'] = ["<a class='stability Unmarked' title='No stability level'></a>impl&lt;R: <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a>&gt; <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a> for <a class='struct' href='compress/bwt/mtf/struct.Decoder.html' title='compress::bwt::mtf::Decoder'>Decoder</a>&lt;R&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;R: <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a>&gt; <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a> for <a class='struct' href='compress/bwt/struct.Decoder.html' title='compress::bwt::Decoder'>Decoder</a>&lt;R&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;R: <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a>&gt; <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a> for <a class='struct' href='compress/flate/struct.Decoder.html' title='compress::flate::Decoder'>Decoder</a>&lt;R&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;R: <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a>&gt; <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a> for <a class='struct' href='compress/lz4/struct.Decoder.html' title='compress::lz4::Decoder'>Decoder</a>&lt;R&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;R: <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a>&gt; <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a> for <a class='struct' href='compress/zlib/struct.Decoder.html' title='compress::zlib::Decoder'>Decoder</a>&lt;R&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;R: <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a>&gt; <a class='trait' href='http://doc.rust-lang.org/master/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a> for <a class='struct' href='compress/entropy/ari/table/struct.ByteDecoder.html' title='compress::entropy::ari::table::ByteDecoder'>ByteDecoder</a>&lt;R&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
